import pandas as pd
import os
import time

def generate_and_save_plots():
    """
    Creates a DataFrame containing the 50 LLM-generated plot summaries
    for cold-start movies and saves it to a CSV file.
    """
    print("Starting Step 3: Generating and saving LLM-augmented data...")
    start_time = time.time()

    # This list contains all 50 synthesized plot summaries for the cold-start movies.
    #
    generated_data = [
        {'title': 'Pokémon the Movie: White - Victini and Zekrom (2011)', 'plot': "A young Pokémon trainer arrives in Eindoak Town to compete in a tournament and befriends the mythical Pokémon Victini. A descendant of the town's ancient people, Damon, seeks to restore his ancestral kingdom by moving the town's castle, the Sword of the Vale, using Victini's life force. This plan, however, threatens to unleash a destructive energy upon the world. The trainer must rally his friends and the legendary dragon Pokémon Reshiram to stop Damon's misguided quest, save Victini, and prevent a global catastrophe in a climactic battle."},
        {'title': 'Virgin Territory (2007)', 'plot': "In 14th-century Florence, during the ravages of the Black Death, a beautiful noblewoman named Pampinea flees to a secluded convent to escape an arranged marriage to a ruthless nobleman. At the same time, a charming rogue, Lorenzo, takes refuge at the convent, pretending to be a deaf-mute gardener to hide from the same nobleman. Amidst a backdrop of spirited and repressed nuns, a tale of mistaken identities and romantic pursuits unfolds. Pampinea and Lorenzo must navigate the deceptions within the convent walls while evading their common enemy who is determined to claim his prize."},
        {'title': 'Boxing Gym (2010)', 'plot': "This documentary provides a non-narrative, observational look inside a local boxing gym in Austin, Texas. Without interviews or a formal story arc, the film captures the daily rhythms and routines of a diverse group of fighters. Men and women of all ages, races, and social classes train, spar, and interact with one another and their coaches. The gym itself, with its numerous mirrors, becomes a powerful metaphor for self-reflection and discipline. The film focuses on the raw sounds and movements of training—the thud of gloves on bags, the scrape of shoes on the canvas, and the quiet moments of concentration—to paint a portrait of a community built around the shared pursuit of the sport."},
        {'title': 'Shooting Gallery (2005)', 'plot': "A talented but naive pool player gets drawn into the dangerous world of high-stakes underground hustling. He quickly learns that his skills at the table can earn him fast money but also attract the attention of a ruthless crime boss who controls the games. Initially seduced by the lifestyle, he soon finds himself trapped in a web of deceit, betrayal, and violence. He is forced to play a series of increasingly dangerous games where the stakes are not just money, but his own life. To survive, he must outwit his menacing patron and navigate the treacherous rules of the criminal underworld, leading to a final, high-stakes showdown."},
        {'title': 'A Good Marriage (2014)', 'plot': "After twenty-seven years of a happy, stable marriage, Darcy Anderson discovers a dark secret about her husband, Bob. While searching for batteries in their garage, she stumbles upon a box containing the ID of a recent victim of a notorious serial killer known as 'Beadie'. Cross-referencing Bob's business travel records with the locations of the murders, she confirms the horrifying truth: her husband is the killer. When Bob realizes she knows, he calmly explains his dark impulses. Darcy must then decide whether to expose the man she loves to protect future victims or to keep the secret to protect her family, leading to a tense psychological battle of wits under their own roof."},
        {'title': 'The Prophecy: Forsaken (2005)', 'plot': "Allison, the chosen one, is still protecting a cursed ancient scripture from a legion of rebellious angels. When the book accidentally opens, she is possessed by a spirit, and the angels, led by a new and ambitious commander, intensify their hunt. They believe the book's prophecies will reveal the name of the Antichrist and end the war between angels. Allison must fight the internal battle against her possession while being pursued on Earth. Her only hope lies in confronting the angel leader and finding a way to reverse the prophecy's course before the war in heaven spills over and consumes all of humanity in its apocalyptic final battle."},
        {'title': 'The First Time (2012)', 'plot': "Dave, a high school senior, is hopelessly in love with his best friend, a popular girl who doesn't see him that way. Aubrey, a junior from a different school, has an older boyfriend who doesn't seem to understand her. During a chance encounter at a party, the two strike up a conversation and feel an instant, witty connection. Over the course of a single weekend, they embark on a series of adventures, sharing their vulnerabilities, insecurities, and dreams. Their budding relationship progresses from awkward flirting to a deeper emotional bond, forcing them to confront their existing relationships and what it truly means to fall in love for the first time."},
        {'title': 'Quo Vadis? (1951)', 'plot': "A victorious Roman commander, Marcus Vinicius, returns to Rome and falls in love with Lygia, a devout Christian woman held as a hostage. His attempts to claim her are thwarted as she escapes into the growing Christian community. As Marcus pursues her, he is gradually exposed to and converted by their faith. Their romance unfolds against the backdrop of Emperor Nero's escalating madness, which culminates in him burning Rome and blaming the Christians for the fire. Marcus and Lygia are arrested and, along with other Christians, sentenced to death in the arena. Their fate incites a public revolt against the tyrannical emperor, leading to Nero's downfall and a new era for Rome."},
        {'title': 'House of Wax (2005)', 'plot': "A group of college friends on their way to a football game get stranded in a strange, remote town after their car breaks down. They soon discover the town's main attraction is a eerily lifelike wax museum. Their curiosity turns to terror when they realize the figures are not wax sculptures, but the wax-coated corpses of previous visitors. The town is run by a pair of disturbed, murderous twin brothers who are expanding their collection by luring in and killing stranded motorists. The friends must fight for their lives and find a way to escape before they become the next permanent exhibits in the horrifying House of Wax."},
        {'title': 'Saving Face (2004)', 'plot': "Wilhelmina, a successful young Chinese-American surgeon in New York, struggles to balance her career, her burgeoning relationship with her dancer girlfriend Vivian, and the expectations of her traditional family. Her carefully managed life is thrown into chaos when her 48-year-old widowed mother, Hwei-Lan, shows up on her doorstep, pregnant and disowned by her own father for refusing to name the baby's father. As Wil navigates her secret romance with Vivian, she is also forced to set her mother up on a series of awkward dates. The film explores the intersecting pressures of cultural tradition, family honor, and personal happiness across generations."},
        {'title': 'Theeya Velai Seiyyanum Kumaru (2013)', 'plot': "Kumar, a young man who has always been unsuccessful in love, falls for Sanjana, a new colleague at his office. Lacking the confidence to approach her, he enlists the help of a 'love guru', a charismatic expert who coaches him on how to win her heart. Following the guru's often comical and elaborate advice, Kumar transforms his image and begins to make progress with Sanjana. However, his schemes are complicated by a rival suitor who is also vying for Sanjana's affection. Kumar must navigate the hilarious and chaotic situations created by his mentor's instructions while trying to be true to himself to ultimately win the girl of his dreams."},
        {'title': 'Blood Work (2002)', 'plot': "A retired FBI profiler, recently recovered from a heart transplant, is pulled back into the world of crime when a woman asks him to investigate the murder of her sister—the very woman whose heart he received. Bound by a unique and personal connection to the victim, he feels obligated to find her killer. As he delves into the case, he uncovers a complex web of clues that seem to be taunting him personally, suggesting the killer knows his identity. The investigation becomes a race against time as he realizes he might be hunting a serial killer he has chased before, all while his fragile health puts his own life at risk."},
        {'title': 'The Raven (2012)', 'plot': "In 19th-century Baltimore, a brilliant but disgraced writer, Edgar Allan Poe, is in a state of creative and financial decline. When a series of gruesome murders begins to plague the city, a young detective makes a shocking discovery: the killer is re-enacting the morbid and elaborate deaths described in Poe's own gothic tales. The writer is pulled from his alcoholic haze and recruited by the police to help them get inside the mind of the serial killer. The deadly cat-and-mouse game becomes intensely personal when the killer kidnaps Poe's beloved fiancée, forcing the writer to participate in the real-life narrative to save her before she becomes the final, tragic character in his own story."},
        {'title': 'The Big Steal (1990)', 'plot': "Danny, a socially awkward teenager, finally gets the car he's always dreamed of—a classic Jaguar—to impress Joanna, the girl he adores. However, the car, bought from a shady dealer, turns out to be a lemon, leading to a disastrous first date. Determined to get his revenge on the dishonest dealer and win back Joanna's affection, Danny enlists the help of his friends. Together, they concoct an elaborate and comical heist to switch the faulty engine of his Jaguar with a new one from another car on the dealer's lot. The plan involves a series of mishaps and clever maneuvers, becoming a hilarious coming-of-age adventure about friendship and first love."},
        {'title': 'The Last Godfather (2010)', 'plot': "The aging head of a powerful mafia family, Don Carini, decides it's time to groom a successor. To the shock of his lieutenants, he reveals a secret, long-lost son named Young-gu, who he has brought over from Korea. However, Young-gu is not a hardened gangster; he is a clumsy, simple-minded, and naive man completely unfit for the mob lifestyle. The Don assigns his top men the frustrating task of training Young-gu in the ways of the mafia. What follows is a series of slapstick comedic disasters as Young-gu's inept attempts at being a gangster create chaos for the organization, all while he accidentally falls for the daughter of a rival mob boss."},
        {'title': 'Go for It! (2011)', 'plot': "A talented young dancer from a tough inner-city neighborhood dreams of pursuing a formal education in dance but faces numerous obstacles, including a lack of support from her family and financial hardship. She spends her days in school and her nights honing her skills in underground dance battles with her crew. When a professor sees her potential, she is encouraged to audition for a prestigious dance academy in Chicago. The story follows her journey of self-discovery as she struggles to bridge the gap between her raw, street-style hip-hop background and the disciplined world of formal dance training, all while navigating challenges in her personal life and friendships."},
        {'title': 'A Haunted House 2 (2014)', 'plot': "After the harrowing and bizarre events of his previous relationship, Malcolm tries to start a new life with his new girlfriend, Megan, and her two children. Moving into what they hope is their dream house, they quickly find that paranormal phenomena have followed them. Malcolm is once again plagued by supernatural occurrences, from a possessed doll to inexplicable events linked to his deceased ex-girlfriend. This time, the hauntings are even more absurd and intrusive. Malcolm must once again resort to a series of ridiculous and slapstick measures, seeking help from a motley crew of amateur exorcists and paranormal investigators to cleanse his home and save his new family from the ghostly mayhem."},
        {'title': 'The Man Who Cried (2000)', 'plot': "In 1927, a young Jewish girl named Fegele is separated from her father in their Russian village. She escapes to England, is renamed Suzie, and discovers a talent for singing. Years later, as a young woman on the eve of World War II, she moves to Paris to join an opera company. There, she befriends a glamorous Russian dancer and falls in love with a mysterious and handsome gypsy horseman. Her life becomes a complex web of love, ambition, and danger as the Nazi threat grows across Europe. She must navigate her relationships and her hidden identity, all while holding onto the hope of one day reuniting with her father in America."},
        {'title': 'The Adventurers (1995)', 'plot': "A skilled fighter pilot's life is shattered when a corrupt rival frames him, leading to the death of his wife and his own imprisonment. Years later, he escapes seeking vengeance. His quest leads him to Cambodia, where his old rival is now a powerful crime lord controlling a vast criminal empire. To get close to his target, the pilot must infiltrate the heavily fortified organization. He teams up with his former partner's daughter, who is also seeking answers and justice. Together, they navigate a dangerous world of high-tech heists and explosive action, working from the inside to dismantle the empire and confront the man who destroyed their lives in a final, decisive showdown."},
        {'title': 'Time to Choose (2015)', 'plot': "This documentary presents a comprehensive and urgent examination of the global climate change crisis, focusing on the available solutions and the choices humanity faces. The film is structured around the three primary drivers of the climate problem: the burning of fossil fuels, rampant deforestation, and unsustainable agriculture practices. Through a series of interviews with experts, innovators, and activists from around the world, the narrative explores the challenges and offers a hopeful perspective by highlighting the viable and scalable solutions that already exist in renewable energy, land restoration, and sustainable food systems. The core message is one of empowerment, arguing that the tools to solve the crisis are at hand, and what is needed is the collective will to act."},
        {'title': 'A Better Life (2011)', 'plot': "Carlos, a hardworking and undocumented immigrant gardener in East Los Angeles, struggles to provide for his teenage son, Luis, and keep him away from the influence of local gangs. He sees a chance to build a better future by purchasing a landscaping truck from his retiring boss. After borrowing the money, he buys the truck, a symbol of hope and independence. However, his dreams are shattered when the truck is stolen by one of his own workers. Carlos and Luis embark on a desperate, day-long search across the sprawling city to recover their stolen property and their only chance at a better life, forcing them to confront their strained relationship and the harsh realities of their existence."},
        {'title': 'Dead End (2003)', 'plot': "On Christmas Eve, the Harrington family takes a shortcut on their way to a holiday gathering. The monotonous drive down an endless, dark forest road soon turns into a nightmare. They encounter a mysterious woman in white holding a baby, and a phantom black hearse that appears to spirit away members of the family one by one. Trapped on a road that never seems to end and from which all turnoffs lead back to the same spot, the family's sanity begins to fray. Secrets are revealed and long-held resentments surface as they realize they are caught in a terrifying, supernatural loop with no escape."},
        {'title': 'Fido (2006)', 'plot': "In an alternate 1950s-style world, humanity has won the 'Zombie Wars', and the dead are now controlled by a corporation called ZomCon, which provides domestic zombies as servants. A young boy named Timmy befriends his family's new zombie, naming him Fido. Their bond is tested when Fido's control collar malfunctions, leading to him accidentally eating a neighbor and starting a small zombie outbreak. Timmy must protect his undead best friend from the zealous head of ZomCon security while navigating the absurdities of a society where the undead are both a status symbol and a constant threat, leading to a darkly comedic and heartwarming tale of friendship."},
        {'title': 'All the Queen\\\'s Men (2001)', 'plot': "During World War II, the Allies are desperate to capture an Enigma code-breaking machine from a German factory staffed entirely by women. After previous attempts fail, a mismatched team of four male Allied soldiers is sent on an audacious undercover mission. The team includes a brash American, a British transvestite, a young genius, and a reluctant Scottish major. Their plan is to infiltrate the factory by dressing as women. Dropped in the wrong location, the men must first navigate hostile territory in their unconvincing disguises. The mission becomes a comedy of errors as they try to blend in, retrieve the machine, and avoid capture, all while challenging their own prejudices."},
        {'title': 'The Greatest Story Ever Told (1965)', 'plot': "This epic film retells the life of Jesus of Nazareth, from his birth in Bethlehem to his crucifixion and subsequent resurrection. The narrative follows his ministry as he gathers his disciples, performs miracles such as feeding the 5,000 and raising Lazarus from the dead, and delivers his famous Sermon on the Mount. The story unfolds against the backdrop of Roman-occupied Judea, detailing his conflict with the Pharisees, his betrayal by Judas Iscariot, and his trial before Pontius Pilate. The film culminates in his journey to Golgotha, his crucifixion between two thieves, and his ultimate ascension, presenting a grand-scale, reverent depiction of the biblical account of his life and its impact on humanity."},
        {'title': 'I\\\'m for the Hippopotamus (1979)', 'plot': "In Africa, two cousins find themselves on opposite sides of a moral and financial conflict. One cousin, a pragmatic businessman, runs a safari business for tourists. The other, an idealistic animal lover, is determined to protect the local wildlife from exploitation. Their disagreements escalate into a series of comedic brawls and one-upmanship. However, they must put aside their differences and team up when a ruthless and powerful German tycoon arrives with a plan to bulldoze the local villages and capture all the wildlife for a foreign zoo. The cousins combine their unique skills in a slapstick, action-packed effort to sabotage the villain's operation and save the animals."},
        {'title': 'Funny Games (2007)', 'plot': "A wealthy family—a husband, wife, and their young son—arrive at their serene lakeside vacation home. Their peace is soon shattered by the arrival of two polite but unnerving young men dressed in white gloves who claim to be guests of the neighbors. The men's visit quickly turns sinister as they refuse to leave and begin to subject the family to a series of sadistic and terrifying 'games'. Trapped in their own home, the family is forced to endure escalating psychological and physical torture. The film unfolds as a horrifying home invasion, where the intruders break not only the family's bodies and wills but also the conventions of cinema, directly addressing the audience in a chilling examination of violence."},
        {'title': 'The Perfect Score (2004)', 'plot': "A diverse group of six high school students, each with their own reasons for needing a high score, feel immense pressure from the upcoming SAT exam. Frustrated by a system they see as unfair and a barrier to their futures—from getting into an Ivy League school to simply keeping a basketball scholarship—they decide to take matters into their own hands. They devise an audacious plan to break into the regional ETS testing center and steal the answers to the exam. The film follows their comical and suspenseful heist as this unlikely team of a jock, a stoner, a rich girl, and others must work together to outsmart the standardized testing system."},
        {'title': 'Grace Is Gone (2007)', 'plot': "A man whose wife, a soldier named Grace, is serving in the Iraq War, struggles to raise their two young daughters. He is a staunch supporter of the war and his wife's service. One day, he receives the devastating news that Grace has been killed in action. Unable to bring himself to tell his daughters, he impulsively decides to take them on a road trip to their favorite amusement park, Enchanted Gardens. The journey becomes a poignant and emotional attempt to postpone the inevitable grief, as he tries to give his daughters one last happy memory before their world is shattered by the tragic news he is withholding."},
        {'title': 'The Order (2003)', 'plot': "A young, disillusioned priest from a secret religious order travels to Rome to investigate the mysterious death of his mentor. His investigation uncovers an ancient and sinister conspiracy within the church itself. He discovers the existence of a 'Sin Eater', a figure who can absorb the souls of the un-absolved, allowing them to enter heaven. As he delves deeper, he finds himself confronting the ultimate evil and a series of dark truths that challenge the very foundations of his faith. He must navigate a treacherous path of secret societies and supernatural forces to uncover the identity of the final Sin Eater and confront his own destiny."},
        {'title': 'Gods and Generals (2003)', 'plot': "This epic historical drama serves as a prequel to the events of the Battle of Gettysburg, focusing on the early years of the American Civil War from 1861 to 1863. The film provides intimate portraits of the key military figures who would become legends, particularly Confederate Lieutenant General Thomas 'Stonewall' Jackson. It explores his deep religious convictions and brilliant military tactics through the major early battles, including Bull Run, Fredericksburg, and Chancellorsville. The narrative also follows the experiences of Union Colonel Joshua Lawrence Chamberlain, depicting the personal sacrifices, strategic challenges, and ideological conflicts that defined the initial, brutal phase of the war, setting the stage for the conflict's most famous confrontation."},
        {'title': 'The Prince & Me II: The Royal Wedding (2006)', 'plot': "Shortly after the events of their courtship, the newly crowned King of Denmark and his American fiancée, a former pre-med student, are preparing for their lavish royal wedding. However, their plans are thrown into turmoil when an old law is discovered: if the King marries a commoner who has not been approved by the nobility, he must abdicate the throne. This revelation gives an old rival a chance to interfere and claim the throne for himself. The couple must navigate the treacherous waters of royal protocol, political intrigue, and public scrutiny to prove their love is strong enough to overcome ancient traditions and secure their future together on the Danish throne."},
        {'title': 'What Women Want (2000)', 'plot': "Nick Marshall, a chauvinistic Chicago advertising executive, believes he is God's gift to women. After a freak accident involving a hairdryer and a bathtub, he wakes up with an extraordinary new ability: he can hear what women are thinking. Initially overwhelmed and horrified by the candid, unfiltered thoughts of his female colleagues, he soon realizes his new power is a secret weapon. He decides to use it to his advantage to sabotage his new boss, a talented woman who got the promotion he thought he deserved. However, as he continues to listen in, he begins to see the world from a different perspective, leading to unexpected personal and romantic growth."},
        {'title': 'The Good Guy (2009)', 'plot': "Ambitious and beautiful New Yorker Beth wants the perfect life: a great job, a nice apartment, and a successful Wall Street boyfriend. She seems to have it all with her handsome, high-powered boyfriend Tommy. When Tommy takes a new, seemingly naive and bookish colleague, Daniel, under his wing, Beth and Daniel strike up a friendship. As Beth spends more time with the charming and grounded Daniel, she begins to question what she truly wants in a partner and a life. She finds herself caught in a love triangle, forced to choose between the flashy, high-stakes world of her original boyfriend and the more sincere, intellectual connection she shares with his protégé."},
        {'title': 'The Return of the Living Dead (1985)', 'plot': "Two bumbling employees at a medical supply warehouse accidentally release a mysterious military chemical that reanimates the dead. The situation spirals out of control when the resulting zombies are discovered to be not only intelligent and fast-moving but also craving human brains. To make matters worse, a group of punk rock teenagers decides to party in the nearby cemetery, unwittingly walking into the epicenter of the zombie outbreak. A darkly comedic and gory battle for survival ensues as the small group of employees and the punks must fend off an army of unstoppable, brain-eating zombies while trying to find a way to contain the spreading horror."},
        {'title': 'The Sweetest Thing (2002)', 'plot': "Christina, a party girl with a cynical view on relationships, unexpectedly meets a man she believes could be 'Mr. Right' during a night out at a club. The next morning, she discovers he has left town. Regretting her decision not to pursue him, she and her equally wild best friend, Courtney, embark on an impromptu road trip to find him at his brother's wedding. Their journey is filled with a series of raunchy, absurd, and hilarious misadventures, from encounters with quirky characters to comical and cringe-worthy situations. The film is a lighthearted romantic comedy focused on female friendship and the chaotic pursuit of love."},
        {'title': 'The Wraith (1986)', 'plot': "A mysterious, black-clad stranger arrives in a desolate Arizona town on a futuristic, super-powered motorcycle. He begins to challenge a ruthless gang of drag-racing thugs who terrorize the local teens and control the roads. One by one, the stranger, who appears to be an otherworldly entity, engages the gang members in deadly races, causing them to crash in fiery explosions. It becomes clear that the stranger is the reincarnated spirit of a teenager who was murdered by the gang's leader years ago. He has returned as an avenging angel, or 'wraith', to eliminate the gang members and rekindle his romance with his former girlfriend."},
        {'title': 'A Woman, a Gun and a Noodle Shop (2009)', 'plot': "In a remote desert town in ancient China, the bitter and cruel owner of a noodle shop learns that his young wife is having an affair with one of his employees. Consumed by jealousy, he secretly hires a corrupt local patrolman to kill the two lovers. However, the patrolman has his own greedy and treacherous plans. The situation quickly spirals out of control into a dark and farcical web of deceit, misunderstanding, and murder. The plot becomes a chaotic chain reaction of double-crosses and mishaps as each character tries to outwit the others, all set against the visually striking and isolated desert landscape. The tone shifts between dark comedy and tense thriller."},
        {'title': 'The Last Shot (2004)', 'plot': "An aspiring screenwriter, desperate to get his first movie made, finally gets his big break when a producer agrees to fund his passion project, a somber drama about a woman with a terminal illness. Unbeknownst to the writer, the 'producer' is actually an FBI agent running an elaborate sting operation to take down a powerful mob boss. The film production is entirely fake, a front designed to lure the mobster into a bribery scheme. The writer, believing his dream is coming true, hires his brother to direct, and together they navigate the bizarre and often comical world of a film set where the crew consists of undercover agents and no one actually intends to make a movie."},
        {'title': 'The Wicker Man (2006)', 'plot': "A highway patrolman receives a desperate letter from his former fiancée, pleading for help in finding her missing young daughter. His investigation leads him to a remote, private island off the coast of Washington, inhabited by a neo-pagan matriarchal community. The secretive and hostile islanders claim the girl never existed. As he delves deeper into the community's strange fertility rites and customs, he uncovers a sinister conspiracy. He begins to suspect the girl is being prepared as a human sacrifice for their upcoming harvest festival. His search becomes a frantic race against time to find the child before he himself becomes entangled in the community's horrifying ritual."},
        {'title': 'The Last Days of Disco (1998)', 'plot': "In the 'very early 1980s', two recent college graduates, Alice and Charlotte, work as low-level editors at a Manhattan publishing house by day and seek romance and social validation at a trendy, exclusive disco nightclub by night. The club serves as the backdrop for their intertwined professional and personal lives, as they navigate the complex social landscape of the era. They interact with a group of ambitious young men, including a charismatic club manager, a depressive lawyer, and an aspiring advertising executive. The narrative explores their conversations, relationships, and anxieties about careers, love, and social status, all set against the fading glamour of the disco era."},
        {'title': 'The Thief and the Cobbler (1995)', 'plot': "In a magnificent, golden city protected by three magical golden balls, a humble and shy cobbler named Tack falls for the beautiful Princess Yum-Yum. Meanwhile, a clumsy, kleptomaniac thief is relentlessly trying to steal the golden balls from the top of the highest minaret. The city's peace is threatened when the evil, one-eyed sorcerer Zigzag, with his army of war machines, plots to conquer the kingdom. When the thief finally succeeds in stealing the balls, the city's protector, an ancient prophecy, is nullified, allowing Zigzag's army to invade. It is up to the simple cobbler Tack and the resourceful princess to embark on a perilous journey to retrieve the magical balls and save their kingdom from destruction."},
        {'title': 'Vampires Suck (2010)', 'plot': "This film is a direct parody of the vampire-themed romantic fantasy genre. A teenage girl named Becca is torn between two mysterious and supernatural boys: a moody, pale vampire named Edward and a consistently shirtless werewolf named Jacob. The plot follows her as she navigates the absurdities of their love triangle and the bizarre local events in her new town. The story spoofs key scenes and character tropes from popular vampire franchises, including intense staring, dramatic slow-motion entrances, and the over-the-top angst of its main characters. It pokes fun at the genre's conventions through a series of slapstick gags, pop culture references, and satirical situations, leading to a comedic and exaggerated climax at the high school prom."},
        {'title': 'The Children (2008)', 'plot': "Two families gather for a relaxing New Year's holiday at a secluded country home. The festive mood soon sours as the young children of both families begin to fall ill with a mysterious sickness. Their illness quickly manifests in terrifying ways, as they turn against their parents with silent, coordinated, and murderous intent. Trapped by a snowstorm and with no way to call for help, the adults are forced into a horrifying battle for survival against their own sweet-faced, now-malevolent offspring. They must confront the unthinkable reality that their children are methodically hunting them, turning a picturesque winter vacation into a desperate and brutal fight for life."},
        {'title': 'Taxi 2 (2000)', 'plot': "A Japanese minister of defense is traveling to Paris to sign a major weapons contract and to observe French anti-gang tactics. However, during his visit, he is kidnapped by a group working for the Japanese yakuza. A young police officer must once again team up with a highly skilled and speed-obsessed taxi driver. Using the driver's heavily modified, high-performance taxi, the duo engages in a series of high-speed chases and comical action sequences through the streets of Paris. They must navigate explosions, incredible stunts, and their own clashing personalities to rescue the minister and thwart the international criminals before the important treaty is jeopardized."},
        {'title': 'B-Movie: Lust & Sound in West-Berlin 1979-1989 (2015)', 'plot': "This documentary captures the raw, creative energy of a decade in West Berlin, seen through the eyes of a British musician who moved to the city in 1979. The film is a collage of archival footage, personal diary entries, and interviews, painting a portrait of a city defined by its political isolation and thriving counter-culture. It explores the collision of post-punk, industrial noise, and early electronic music scenes that flourished in the shadow of the Berlin Wall. The narrative highlights the key figures and bands of the era, showcasing a unique subculture where economic hardship and political tension fueled radical artistic experimentation, culminating in the city's transformation after the fall of the Wall."},
        {'title': 'The Fearless Vampire Killers (1967)', 'plot': "A bumbling, elderly professor and his timid young assistant travel to a remote Transylvanian village on the hunt for vampires. They find lodging at a local tavern where the innkeeper's beautiful daughter is promptly kidnapped by the local vampire lord, Count von Krolock. Determined to rescue her, the duo infiltrates the Count's ominous castle. Inside, they must navigate a bizarre and comical series of events, including contending with the Count's foppish, homosexual son who takes an immediate liking to the assistant. Their rescue attempt culminates at a grand ball attended by a host of aristocratic vampires, forcing the inept hunters to find a way to save the girl and escape the castle of the undead."},
        {'title': 'The Adventures of Elmo in Grouchland (1999)', 'plot': "The story begins when the main character, a small, cheerful red monster, refuses to share his beloved blue blanket. A tug-of-war results in the blanket being accidentally thrown into the trash can of his grumpy, garbage-dwelling neighbor. In his attempt to retrieve it, he and the blanket are sucked through a colorful vortex at the bottom of the can, landing in Grouchland, a world filled with grouchy creatures and mountains of trash. The blanket is then stolen by the greedy and villainous Huxley, who believes in owning everything. The young monster must embark on an epic quest, facing challenges and meeting quirky new friends, to confront Huxley and rescue his prized possession."},
    ]

    # Create a pandas DataFrame from the list of dictionaries
    generated_plots_df = pd.DataFrame(generated_data)

    # Save the DataFrame to a CSV file in the root directory
    save_path = 'generated_plots.csv'
    generated_plots_df.to_csv(save_path, index=False)

    end_time = time.time()
    print("\n--- Success! ---")
    print(f"Process finished in {end_time - start_time:.2f} seconds.")
    print(f"All {len(generated_plots_df)} generated plots have been saved to '{save_path}'.")


if __name__ == '__main__':
    generate_and_save_plots()